import argparse
import gzip
import pickle
import sys
from pathlib import Path

import numpy as np

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "third_party" / "utils_simba"))

from robust_hoi_pipeline.frame_management import load_register_indices
from robust_hoi_pipeline.pipeline_joint_opt import (
    _joint_optimize_keyframes,
    _stack_intrinsics,
    load_preprocessed_data,
    load_tracks,
    save_results,
)


def _load_image_info(joint_opt_dir: Path, excluded_global=False) -> dict:
    """Load the latest image_info from pipeline_joint_opt output (gzip pickle)."""
    register_indices = load_register_indices(joint_opt_dir)
    last_iter = -1
    last_register_idx = register_indices[last_iter]
    while excluded_global: 
        if register_indices[last_iter] < 9900:
            last_register_idx = register_indices[last_iter]
            break
        last_iter -= 1

    frame_dir = joint_opt_dir / f"{last_register_idx:04d}"

    info_path = frame_dir / "image_info.pkl.gz"
    with gzip.open(info_path, "rb") as f:
        image_info = pickle.load(f)

    shared_path = joint_opt_dir / "shared_info.pkl.gz"
    if shared_path.exists():
        with gzip.open(shared_path, "rb") as f:
            shared = pickle.load(f)
        shared.update(image_info)
        image_info = shared

    print(f"Loaded image_info from {info_path} (last_register_idx={last_register_idx})")
    return image_info


def main(args):
    result_dir = Path(args.result_dir)
    data_dir = Path(args.data_dir)

    joint_opt_dir = result_dir / "pipeline_joint_opt"

    # Load the latest image info generated by robust_hoi_pipeline/pipeline_joint_opt.py
    image_info = _load_image_info(joint_opt_dir, excluded_global=True)

    frame_indices = image_info["frame_indices"]
    cond_idx = int(image_info["cond_idx"])
    cond_local_idx = frame_indices.index(cond_idx)

    print(f"Loaded {len(frame_indices)} frames, cond_idx={cond_idx} (local={cond_local_idx})")
    print(f"Keyframes: {int(np.array(image_info['keyframe']).sum())}, "
          f"registered: {int(np.array(image_info['register']).sum())}")

    # Reconstruct image_info_work: reload tracks and depth priors from original data
    data_preprocess_dir = data_dir / "pipeline_preprocess"
    tracks_dir = data_dir / "pipeline_corres"

    preprocessed_data = load_preprocessed_data(data_preprocess_dir, frame_indices)
    track_data = load_tracks(tracks_dir)
    tracks = track_data["tracks"]
    vis_scores = track_data["vis_scores"]
    tracks_mask = track_data["tracks_mask"] & (vis_scores >= 0.4)

    intrinsics = _stack_intrinsics(preprocessed_data["intrinsics"])
    c2o = np.asarray(image_info["c2o"], dtype=np.float64)
    extrinsics = np.linalg.inv(c2o).astype(np.float32)

    image_info_work = {
        "frame_indices": frame_indices,
        "pred_tracks": tracks.astype(np.float32),
        "track_mask": tracks_mask.astype(bool),
        "points_3d": np.asarray(image_info["points_3d"], dtype=np.float32),
        "extrinsics": extrinsics,
        "intrinsics": intrinsics,
        "depth_priors": preprocessed_data["depths"],
        "image_masks": preprocessed_data.get("masks_obj"),
        "keyframe": np.asarray(image_info["keyframe"], dtype=bool),
        "registered": np.asarray(image_info["register"], dtype=bool),
        "invalid": np.asarray(image_info["invalid"], dtype=bool),
    }

    # Find the latest NeuS mesh in joint_opt_dir/neus_training (if any)
    neus_training_dir = joint_opt_dir / "neus_training"
    neus_mesh_path = None
    # if neus_training_dir.exists():
    #     obj_files = sorted(neus_training_dir.rglob("*.obj"), key=lambda p: p.stat().st_mtime)
    #     if obj_files:
    #         neus_mesh_path = obj_files[-1]
    #         print(f"Using NeuS mesh: {neus_mesh_path}")
    #     else:
    #         print("No NeuS mesh found; point-to-plane loss will be disabled.")
    # else:
    #     print(f"NeuS training dir not found ({neus_training_dir}); skipping mesh.")

    # Optimize all keyframes jointly with 1000 iterations
    print(f"Running global joint keyframe optimization (num_iters=1000) ...")
    _joint_optimize_keyframes(
        image_info_work,
        neus_mesh_path=neus_mesh_path,
        cond_local_idx=cond_local_idx,
        num_iters=args.num_iters,
    )
    print("Global optimization complete.")

    # Write optimized poses and 3D points back into image_info
    image_info["invalid"] = image_info_work["invalid"].tolist()
    image_info["keyframe"] = image_info_work["keyframe"].tolist()
    image_info["c2o"] = np.linalg.inv(image_info_work["extrinsics"]).astype(np.float32)
    image_info["points_3d"] = image_info_work["points_3d"].astype(np.float32)
    n_frames = len(frame_indices)
    image_info.setdefault("depth_points_obj", [None] * n_frames)
    image_info.setdefault("depth_after_PnP", [None] * n_frames)
    image_info.setdefault("depth_after_align_mesh", [None] * n_frames)
    image_info.setdefault("depth_after_keyframes_opt", [None] * n_frames)
    image_info.setdefault("depth_after_reset_when_pnp_fail", [None] * n_frames)
    image_info["tracks_mask"] = tracks_mask

    # Save image_info with frame index 9999 and update the register order file
    save_results(
        image_info=image_info,
        register_idx=9999,
        preprocessed_data={},
        results_dir=joint_opt_dir,
    )
    print(f"Saved globally optimized image_info to {joint_opt_dir}/9999/")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Global joint keyframe optimization over all registered keyframes."
    )
    parser.add_argument("--result_dir", type=str, required=True,
                        help="Path to output/<seq> directory")
    parser.add_argument("--data_dir", type=str, required=True,
                        help="Path to dataset sequence directory (e.g. HO3D_v3/train/MC1)")
    parser.add_argument("--num_iters", type=int, default=2000,
                        help="Number of iterations for joint optimization")
    return parser.parse_args()


if __name__ == "__main__":
    main(parse_args())
